#!/usr/bin/env python3
"""Generate data.js from source JSONs for offline/landing page use."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "data.js"

FILES = {
    "SOURCES_DATA": ROOT / "sources.json",
    "CLASIC_DATA": ROOT / "clasic.sources.json",
    "PAL_DATA": ROOT / "pal.sources.json",
}


def main():
    lines = ["// Auto-generated by build.py — do not edit manually", ""]
    for var_name, path in FILES.items():
        data = json.loads(path.read_text(encoding="utf-8"))
        lines.append(f"var {var_name} = {json.dumps(data, indent=2, ensure_ascii=False)};")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {OUT.name}")


if __name__ == "__main__":
    main()
